dkd:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: dkd
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    password: root@123456
  sms:
    key:
    secret:
    sign-name: 阿里云短信测试
    template-code: SMS_154950909
